---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: ocp-thunt-1
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: ocp-thunt-1
  labels:
    name: ocp-thunt-1
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: gitops-clusters
spec:
  hubAcceptsClient: true
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: auto-import-secret
  namespace: ocp-thunt-1
stringData:
  autoImportRetry: "2"
  token: sha256~X-X2Oi7hiaVi4NUFlDL7yvdLrvc7FeGzRkvpgDKCXH8
  server: https://api.ocp-thunt-1.89dtg.azure.redhatworkshops.io:6443
type: Opaque
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: ocp-thunt-1
  namespace: ocp-thunt-1
spec:
  clusterName: ocp-thunt-1
  clusterNamespace: ocp-thunt-1
  clusterLabels:
    name: ocp-thunt-1
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: gitops-clusters
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
